export const INDEX_PLAQUE = 0;
export const INDEX_DATE_PREMIERE_IMMATRICULATION = 1;
export const INDEX_MARQUE = 2;
export const INDEX_MODELE = 3;
export const INDEX_MOTEUR = 4;
export const INDEX_TYPE = 5;
export const INDEX_DATE_DERNIERE_IMMATRICULATION = 6;
export const INDEX_IMPOSABLE = 7;
export const INDEX_TYPE_VEHICULE_VOULU = 8;
export const INDEX_ETAT_VEHICULE_VOULU = 9;
export const INDEX_GRAND_ROULEUR = 10;

export const DATE_LIMITE_DIESEL_NON_IMPOSABLE = new Date('01/01/2006');
export const DATE_LIMITE_DIESEL_IMPOSABLE = new Date('01/01/2001');
export const DATE_LIMITE_ESSENCE = new Date('01/01/1997');

export const MONTANT_PRIME_IMPOSABLE_ESSENCE_NEUF = 1000;
export const MONTANT_PRIME_IMPOSABLE_ESSENCE_OCCASION = 1000;
export const MONTANT_PRIME_IMPOSABLE_DIESEL_NEUF = 0;
export const MONTANT_PRIME_IMPOSABLE_DIESEL_OCCASION = 0;
export const MONTANT_PRIME_IMPOSABLE_ELECTRIQUE_HYBRIDE_NEUF = 2500;
export const MONTANT_PRIME_IMPOSABLE_ELECTRIQUE_HYBRIDE_OCCASION = 1000;

export const MONTANT_PRIME_NON_IMPOSABLE_ESSENCE_NEUF = 2000;
export const MONTANT_PRIME_NON_IMPOSABLE_ESSENCE_OCCASION = 2000;
export const MONTANT_PRIME_NON_IMPOSABLE_DIESEL_NEUF = 2000;
export const MONTANT_PRIME_NON_IMPOSABLE_DIESEL_OCCASION = 2000;
export const MONTANT_PRIME_NON_IMPOSABLE_ELECTRIQUE_HYBRIDE_NEUF = 2500;
export const MONTANT_PRIME_NON_IMPOSABLE_ELECTRIQUE_HYBRIDE_OCCASION = 2500;

export const MONTANT_PRIME_IMPOSABLE_MOTO_ELECTRIQUE = 100;
export const MONTANT_PRIME_NON_IMPOSABLE_MOTO_ELECTRIQUE = 1100;

export const LIST_MONTANT_IMPOSABLE = [MONTANT_PRIME_IMPOSABLE_ESSENCE_NEUF,
									   MONTANT_PRIME_IMPOSABLE_ESSENCE_OCCASION,
									   MONTANT_PRIME_IMPOSABLE_DIESEL_NEUF,
									   MONTANT_PRIME_IMPOSABLE_DIESEL_OCCASION,
									   MONTANT_PRIME_IMPOSABLE_ELECTRIQUE_HYBRIDE_NEUF,
									   MONTANT_PRIME_IMPOSABLE_ELECTRIQUE_HYBRIDE_OCCASION,
									   MONTANT_PRIME_IMPOSABLE_MOTO_ELECTRIQUE];

export const LIST_MONTANT_NON_IMPOSABLE = [MONTANT_PRIME_NON_IMPOSABLE_ESSENCE_NEUF,
										   MONTANT_PRIME_NON_IMPOSABLE_ESSENCE_OCCASION,
										   MONTANT_PRIME_NON_IMPOSABLE_DIESEL_NEUF,
										   MONTANT_PRIME_NON_IMPOSABLE_DIESEL_OCCASION,
										   MONTANT_PRIME_NON_IMPOSABLE_ELECTRIQUE_HYBRIDE_NEUF,
										   MONTANT_PRIME_NON_IMPOSABLE_ELECTRIQUE_HYBRIDE_OCCASION,
										   MONTANT_PRIME_NON_IMPOSABLE_MOTO_ELECTRIQUE];
